name = "ParametricTypeExample"
uuid = "ce38909f-b213-51a9-b234-41e92fdcba6c"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
